#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders if required
mkdir -p \
    "${DATADIR}" \
    /config/log/mysql \
    /run/mysqld

# copy custom cnf file
if [[ ! -f /config/custom.cnf ]]; then
    cp /defaults/custom.cnf /config/custom.cnf
fi

# remove orphan pid file
if [[ -f /run/mysqld/mysqld.pid ]]; then
    rm -f /run/mysqld/mysqld.pid
fi
