#!/usr/bin/with-contenv bash

_term() {
    echo "Caught SIGTERM signal!"
    kill -TERM "$(cat /var/run/mysqld/mysqld.pid)" 2>/dev/null
}

trap _term SIGTERM

s6-setuidgid abc \
    /usr/bin/mysqld_safe \
    --console \
    --bind-address=0.0.0.0 \
    --skip-name-resolve \
    --skip-networking=0 \
    --datadir="${DATADIR}" \
    --user=abc &

wait
