#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ "${#MYSQL_ROOT_PASSWORD}" -gt "3" ]]; then
    # display a message about upgrading database if needed
    if mariadb-upgrade -u root -p"${MYSQL_ROOT_PASSWORD}" --check-if-upgrade-is-needed >/dev/null 2>&1; then
        cat <<-EOF



#################################################################
#                                                               #
#           An upgrade is required on your databases.           #
#                                                               #
#         Stop any services that are accessing databases        #
#          in this container, and then run the command          #
#                                                               #
#             mariadb-upgrade -u root -p<PASSWORD>              #
#                                                               #
#################################################################



EOF
        sleep 5s
    fi
fi
