name: Package Trigger Scheduler

on:
  schedule:
    - cron:  '34 12 * * 3'
  workflow_dispatch:

jobs:
  package-trigger-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: '0'
        
      - name: Package Trigger Scheduler
        run: |
          git for-each-ref --format='%(refname:short)' refs/remotes
          docker pull ghcr.io/linuxserver/yq
          for br in $(git for-each-ref --format='%(refname:short)' refs/remotes)
          do
            br=$(echo "$br" | sed 's|origin/||g')
            echo "Evaluating branch ${br}"
            ls_branch=$(curl -sX GET https://raw.githubusercontent.com/linuxserver/docker-mariadb/${br}/jenkins-vars.yml \
              | docker run --rm -i --entrypoint yq ghcr.io/linuxserver/yq -r .ls_branch)
            if [ "${br}" == "${ls_branch}" ]; then
              echo "Branch ${br} appears to be live; triggering."
              if curl -sfX GET https://raw.githubusercontent.com/linuxserver/docker-mariadb/${br}/.github/workflows/package_trigger.yml > /dev/null 2>&1; then
                echo "Workflow exists. Triggering package trigger workflow for branch ${br}."
                curl -iX POST \
                  -H "Authorization: token ${{ secrets.CR_PAT }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -d "{\"ref\":\"refs/heads/${br}\"}" \
                  https://api.github.com/repos/linuxserver/docker-mariadb/actions/workflows/package_trigger.yml/dispatches
                sleep 30
              else
                echo "Workflow doesn't exist; skipping trigger."
              fi
            else
              echo "${br} appears to be a dev branch; skipping trigger."
            fi
          done
